name: Make WASM Build
on: [push]

env:
  EM_VERSION: 3.1.14
  EM_CACHE_FOLDER: 'emsdk-cache'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup cache
      id: cache-system-libraries
      uses: actions/cache@v2
      with:
        path: ${{env.EM_CACHE_FOLDER}}
        key: ${{env.EM_VERSION}}-${{ runner.os }}

    - name: Install Emscripten
      uses: mymindstorm/setup-emsdk@v11
      with: 
        version: ${{env.EM_VERSION}}
        actions-cache-folder: ${{env.EM_CACHE_FOLDER}}

    - name: Building WASM bundle
      run: make app

    - name: Directory listing..
      run: ls -la

    - name: Publish build
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist


